cd /home/maxm/go//src/github.com/voltusdev/
git clone git@github.com:voltusdev/ampere.git
git clone git@github.com:voltusdev/pdfstatement.git
git clone git@github.com:voltusdev/automate-peak-saver.git
git clone git@github.com:voltusdev/peak_saver.git
git clone git@github.com:voltusdev/caret.git
git clone git@github.com:voltusdev/pipeline.git
git clone git@github.com:voltusdev/command-challenge-jessica-sd.git
git clone git@github.com:voltusdev/pkg.git
git clone git@github.com:voltusdev/crutches.git
git clone git@github.com:voltusdev/rawggregator.git
git clone git@github.com:voltusdev/customer-tpl.git
git clone git@github.com:voltusdev/rtpoller.git
git clone git@github.com:voltusdev/dart-submission.git
git clone git@github.com:voltusdev/salesforce-etl.git
git clone git@github.com:voltusdev/deploy-utils.git
git clone git@github.com:voltusdev/scada.git
git clone git@github.com:voltusdev/dlc-settlement.git
git clone git@github.com:voltusdev/scranta.git
git clone git@github.com:voltusdev/takehome-jessica-sd.git
git clone git@github.com:voltusdev/dwolla-client.git
git clone git@github.com:voltusdev/telegraf-stats.git
git clone git@github.com:voltusdev/dwolla-poller.git
git clone git@github.com:voltusdev/tos.git
git clone git@github.com:voltusdev/earnings-dashboard-js.git
git clone git@github.com:voltusdev/trading.git
git clone git@github.com:voltusdev/earnings_dash.git
git clone git@github.com:voltusdev/ux.git
git clone git@github.com:voltusdev/em_baselines.git
git clone git@github.com:voltusdev/voc-js.git
git clone git@github.com:voltusdev/enablement-data-tools.git
git clone git@github.com:voltusdev/voc-mockup.git
git clone git@github.com:voltusdev/engineering.git
git clone git@github.com:voltusdev/voltapp-compose.git
git clone git@github.com:voltusdev/flower-server.git
git clone git@github.com:voltusdev/gittest.git
git clone git@github.com:voltusdev/voltapp-flask.git
git clone git@github.com:voltusdev/golang-base.git
git clone git@github.com:voltusdev/voltapp-nginx.git
git clone git@github.com:voltusdev/hertzus.git
git clone git@github.com:voltusdev/voltapp-react.git
git clone git@github.com:voltusdev/infra.git
git clone git@github.com:voltusdev/voltappclient-go.git
git clone git@github.com:voltusdev/ingest-py.git
git clone git@github.com:voltusdev/voltlet-configurator.git
git clone git@github.com:voltusdev/interval-utils.git
git clone git@github.com:voltusdev/voltlet-system.git
git clone git@github.com:voltusdev/voltlet_deploy.git
git clone git@github.com:voltusdev/loadforecast.git
git clone git@github.com:voltusdev/voltlet_update_scripts.git
git clone git@github.com:voltusdev/mail-handler.git
git clone git@github.com:voltusdev/voltus.git
git clone git@github.com:voltusdev/voltus-command-challenge-terry-smith-dc.git
git clone git@github.com:voltusdev/metering.git
git clone git@github.com:voltusdev/voltus-js-auth.git
git clone git@github.com:voltusdev/miso-edr-bids.git
git clone git@github.com:voltusdev/voltus-js-util.git
git clone git@github.com:voltusdev/miso-notifier.git
git clone git@github.com:voltusdev/voltus-theme.git
git clone git@github.com:voltusdev/mockups.git
git clone git@github.com:voltusdev/voltus-visual.git
git clone git@github.com:voltusdev/mono.git
git clone git@github.com:voltusdev/wayback-api.git
git clone git@github.com:voltusdev/openadr_docs.git

cd /home/maxm/go/src/github.com/maxmcd
git clone git@github.com:maxmcd/rivet.git
git clone git@github.com:maxmcd/how-sqlite-works.git
git clone git@github.com:maxmcd/gitkit.git
git clone git@github.com:maxmcd/circleci-machine.git
git clone git@github.com:maxmcd/splash.git
git clone git@github.com:maxmcd/10kb.site.git
git clone git@github.com:maxmcd/eric-face.git
git clone git@github.com:maxmcd/spotify-fresh.git
git clone git@github.com:maxmcd/util.git
git clone git@github.com:maxmcd/qdm.git
git clone git@github.com:maxmcd/ast-types.git
git clone git@github.com:maxmcd/maxmcd.com.git
git clone git@github.com:maxmcd/worm_scraper.git
git clone git@github.com:maxmcd/zxing_cpp.rb.git
git clone git@github.com:maxmcd/webrtc-builds.git
git clone git@github.com:maxmcd/quipcity-api.git
git clone git@github.com:maxmcd/shopthat-calculator.git
git clone git@github.com:maxmcd/resume.git
git clone git@github.com:maxmcd/fresh.git
git clone git@github.com:maxmcd/fusl.git
git clone git@github.com:maxmcd/commentformatter.git
git clone git@github.com:maxmcd/shopthat/docs/wiki.git
git clone git@github.com:maxmcd/shopthat.git
git clone git@github.com:maxmcd/bristle.git
git clone git@github.com:maxmcd/plum.git
git clone git@github.com:maxmcd/gstreamer-docker.git
git clone git@github.com:maxmcd/caredapp.git
git clone git@github.com:maxmcd/st.git
git clone git@github.com:maxmcd/ESP8266.git
git clone git@github.com:maxmcd/openvpn.git
git clone git@github.com:maxmcd/so.git
git clone git@github.com:maxmcd/docker-janus.git
git clone git@github.com:maxmcd/pi.git
git clone git@github.com:maxmcd/interview-prep.git
git clone git@github.com:maxmcd/gstreamer-rs.git
git clone git@github.com:maxmcd/adventofcode.git
git clone git@github.com:maxmcd/rustcoin.git
git clone git@github.com:maxmcd/voltus.git
git clone git@github.com:maxmcd/fazer-r.git
git clone git@github.com:maxmcd/collab.git
git clone git@github.com:maxmcd/dcdn.git
git clone git@github.com:maxmcd/react-native-ijkplayer.git
git clone git@github.com:maxmcd/react-native-webrtc.git
git clone git@github.com:maxmcd/v8worker2.git
git clone git@github.com:maxmcd/blackbird.git
git clone git@github.com:maxmcd/react-native-wowza-gocoder.git
git clone git@github.com:maxmcd/react-native-onesignal.git
git clone git@github.com:maxmcd/sorting.git
git clone git@github.com:maxmcd/data-structures-and-algorithms.git
git clone git@github.com:maxmcd/deno-docker.git
git clone git@github.com:maxmcd/tfi-supercore.git
git clone git@github.com:maxmcd/c4.git
git clone git@github.com:maxmcd/fan.git
git clone git@github.com:maxmcd/heybutts.com.git
git clone git@github.com:maxmcd/tartan.git
git clone git@github.com:maxmcd/superhawk.git
git clone git@github.com:maxmcd/ideas.git
git clone git@github.com:maxmcd/quipcity-app.git
git clone git@github.com:maxmcd/personal-dev.git
git clone git@github.com:maxmcd/dockerfiles.git
git clone git@github.com:maxmcd/react-native-websocket.git
git clone git@github.com:maxmcd/FlappyBird.git
git clone git@github.com:maxmcd/packer-templates.git
git clone git@github.com:maxmcd/launa.git
git clone git@github.com:maxmcd/qr-note.git
git clone git@github.com:maxmcd/9x16.git
git clone git@github.com:maxmcd/react-syntax-highlighter.git
git clone git@github.com:maxmcd/mem.git
git clone git@github.com:maxmcd/docker-alpine-glibc.git
